feat: create auth pages and logic
dmytropihur/linkstagram pull request #1
Opened 2022-07-12 14:10 UTC by dmytropihur

2022-07-13 10:37 UTC, vovataras requested changes

2022-07-13 10:37 UTC, vovataras commented on core/config/constants.ts
> +export const BASE_URL = 'https://linkstagram-api.linkupst.com';
в чому сенс тримати дві змінні?

2022-07-13 10:37 UTC, vovataras commented on package.json
> +    "@linkupst/eslint-config-react": "^1.0.9",
в devDependencies

2022-07-13 10:37 UTC, vovataras commented on package.json
> +    "@types/react-redux": "^7.1.24",
в devDependencies

2022-07-13 10:37 UTC, vovataras commented on pages/_app.tsx
> +  // eslint-disable-next-line react/jsx-props-no-spreading
краще це правило розмістити де використовується спред і видалити глобальне правило

2022-07-13 10:37 UTC, vovataras commented on pages/api/hello.ts
>  }
цей файл тобі не потрібний, як і вся папка, бо ти не будеш писати api ендпоінти

2022-07-13 10:37 UTC, vovataras commented on ui/components/Button/Button.module.scss
> +  // line-height: 1.3;
?

2022-07-13 10:37 UTC, vovataras commented on ui/components/Button/Button.tsx
> +      type="submit"
всі кнопки будуть `submit`?

2022-07-13 10:37 UTC, vovataras commented on ui/components/Button/Button.tsx
> +      {text}
краще зробити через children, так кнопка буде більше реюзабельною, якщо наприклад туди треба буде передати, щось ще окрім стрічки

2022-07-13 10:37 UTC, vovataras commented on ui/components/Avatar/Avatar.tsx
> +            />
в next по можливості краще використовувати next/image

2022-07-13 10:37 UTC, vovataras commented on ui/components/Avatar/Avatar.tsx
> +      </a>
верстка відрізняється лише назвами класів, тому краще звести до одного і міняти лише класи за певної умови

2022-07-13 10:37 UTC, vovataras commented on ui/components/Avatar/Avatar.tsx
> +const Avatar: NextPage<AvatarProps> = ({ size, gradient }) => {
NextPage тип використовується лише для сторінок (які розміщуються в папці pages), а це компонента

2022-07-13 10:37 UTC, vovataras commented on ui/components/Form/Form.tsx
> +    >
IMHO як показала практика, краще використовувати хук useFormik, тому що він більш кастомізований і дозволяє працювати зі  стейтом форми напряму
p.s. це не обов'язково переписувати, бо, можливо, цього вистачить

2022-07-13 10:37 UTC, vovataras commented on ui/components/Form/Form.tsx
> +const Form: NextPage<FormProps> = ({
React.FC бо NextPage тільки для сторінок

2022-07-13 10:37 UTC, vovataras commented on ui/components/Form/Form.tsx
> +                <Link href="/login">
для лінків краще зробити файл констант routes де буде зберігатись об'єкт зі всіма роутами

2022-07-13 10:37 UTC, vovataras commented on ui/components/Form/Form.tsx
> +import { Formik, Form as Frm, Field, ErrorMessage } from 'formik';
Form краще було назвати як FormikForm, а не Frm

2022-07-13 10:37 UTC, vovataras commented on ui/components/Form/Form.tsx
> +import { AuthProps } from '../../../core/store/user/types';
щоб не писати такі довгі шляхи, можна зробити path aliases (це не обов'язково, а по бажанні, якщо будеш мати час)

2022-07-13 10:37 UTC, vovataras commented on ui/components/Avatar/Avatar.module.scss
> +  filter: drop-shadow(0px 0px 1px rgba(0, 0, 0, 0.5));
фільтр повторюється, його можна винести в змінну

2022-07-13 10:37 UTC, vovataras commented on ui/components/Avatar/Avatar.module.scss
> +  width: 32px;
такий невеликий хак, можна задавати розміри в ремах і тоді менше треба буде гратися з респонсівом, якщо міняти глобально розмір шрифту на певних брейкпоінтах. А для полегшення обрахунків з rem можна створити scss функцію, яка буде приймати px, а повертати rem

2022-07-13 10:37 UTC, vovataras commented on ui/components/Avatar/Avatar.module.scss
> +  justify-content: center;
таке можна виносити в міксини

2022-07-13 10:37 UTC, vovataras commented on ui/components/Header/Header.module.scss
> +  background-color: #fff;
краще через змінну

2022-07-13 10:37 UTC, vovataras commented on ui/components/Header/Header.tsx
> +        <Link href="/">
лінки в константи routes

2022-07-13 10:37 UTC, vovataras commented on ui/components/Header/Header.tsx
> +              </Link>
для Link можна зробити власну компоненту обгортку, яка примайтиме пропси для a і для Link і прокидатиме їх і так не треба буде всюди писати <Link><a>...

2022-07-13 10:37 UTC, vovataras commented on ui/components/Layout/Layout.tsx
> +const Layout: NextPage<LayoutProps> = ({ children }) => {
знову не той тип

2022-07-13 10:37 UTC, vovataras commented on pages/register/index.tsx
> +  );
один в одни як і на логіні, можливо варто зробити спільну компоненту?
і взагалі писати верстку і логіку, яка не стосується static або server side rendering в pages погана практика, для цього є папка views звідки імпортується готова сторінка і вже конектиться в pages

2022-07-13 10:37 UTC, vovataras commented on pages/register/index.tsx
> +      router.push('/login');
лінки в константи

2022-07-13 10:37 UTC, vovataras commented on pages/register/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
для чого це правило?

2022-07-13 10:37 UTC, vovataras commented on ui/styles/Login.module.scss
> +}
специфічні стилі краще тримати ближче до компоненти де вони використовуються

2022-07-13 10:37 UTC, vovataras commented on ui/styles/Register.module.scss
> +}
те саме

2022-07-13 10:37 UTC, vovataras commented on ui/styles/Register.module.scss
> +}
до того ж вони однакові. Чому так???

2022-07-13 10:37 UTC, vovataras commented on core/utils/fetchAccount.tsx
> +export default fetchAccount;
це вже якийсь service а не utils

2022-07-13 10:37 UTC, vovataras commented on core/store/user/slice.ts
> +        // eslint-disable-next-line no-param-reassign
загугли, як вимкнути це правило для файлів `slice` в папці `store`

2022-07-13 10:37 UTC, vovataras commented on core/store/user/slice.ts
> +      const res = await axios.post(`${BASE_API_URL}/create-account`, props);
можна зробити інстанс axios, для якого будуть задані вже якісь загальні параметри по замовчуванню, наприклад, base url

2022-07-13 10:37 UTC, vovataras commented on core/store/user/slice.ts
> +      const { headers } = await axios.post(`${BASE_API_URL}/login`, props);
тут те саме

2022-07-13 11:26 UTC, dmytropihur commented on pages/_app.tsx
> +  // eslint-disable-next-line react/jsx-props-no-spreading
там в jsx розмітці так не получається

2022-07-13 11:26 UTC, dmytropihur commented on package.json
> +    "@types/react-redux": "^7.1.24",
є

2022-07-13 11:26 UTC, dmytropihur commented on package.json
> +    "@linkupst/eslint-config-react": "^1.0.9",
є

2022-07-13 11:26 UTC, dmytropihur commented on core/config/constants.ts
> +export const BASE_URL = 'https://linkstagram-api.linkupst.com';
поправив

2022-07-13 11:27 UTC, dmytropihur commented on pages/api/hello.ts
>  }
видалив

2022-07-13 13:49 UTC, dmytropihur commented on ui/components/Button/Button.tsx
> +      {text}
Поправив

2022-07-13 13:50 UTC, dmytropihur commented on ui/components/Button/Button.tsx
> +      type="submit"
Виправив

2022-07-13 13:50 UTC, dmytropihur commented on ui/components/Avatar/Avatar.tsx
> +      </a>
Виправив

2022-07-15 14:27 UTC, vovataras requested changes

2022-07-15 14:27 UTC, vovataras commented on core/config/constants.ts
> +export default BASE_API_URL;
краще зробити `export default {BASE_API_URL}`, або додати eslint-disable

2022-07-15 14:27 UTC, vovataras commented on ui/components/Button/Button.tsx
> +  type,
добре було б зробити тип 'button' по замовчуванню

2022-07-15 14:27 UTC, vovataras commented on ui/components/Button/Button.tsx
> +          ? styles[`button-${variant}`]
якщо тут будуть і інші варіанти, які будуть підставлятись, то мабуть варто робити лише перевірку, на те, чи є цей варіант і варіант також добре було б протипізувати літералами

2022-07-15 14:27 UTC, vovataras commented on core/store/user/types.ts
> +  registerError: string;
є сенс розділяти еррори? чи краще зробити одну змінну error?

2022-07-15 14:27 UTC, vovataras commented on core/store/user/slice.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
забери це, бо воно не потрібне (перед цим треба нормально встановити @reduxjs/toolkit в основні залежності а не dev)

2022-07-15 14:27 UTC, vovataras commented on core/store/user/slice.ts
> +import BASE_API_URL from '../../config/constants';
імпортуй окремо, а не по замовчуванню, бо є ймовірність, що там будуть ще і інші константи

2022-07-15 14:27 UTC, vovataras commented on pages/_app.tsx
> +        <Component {...pageProps} />
можеш тут над цим рядком зробити коментар через `{/*  */}` і прибрати загальний дісейбл

2022-07-15 14:30 UTC, dmytropihur commented on pages/_app.tsx
> +        <Component {...pageProps} />
пробував так, і воно не діяло

2022-07-16 09:00 UTC, dmytropihur commented on ui/components/Avatar/Avatar.tsx
> +const Avatar: NextPage<AvatarProps> = ({ size, gradient }) => {
Виправив

2022-07-16 09:00 UTC, dmytropihur commented on ui/components/Form/Form.tsx
> +const Form: NextPage<FormProps> = ({
Виправив

2022-07-16 09:01 UTC, dmytropihur commented on ui/components/Form/Form.tsx
> +import { Formik, Form as Frm, Field, ErrorMessage } from 'formik';
Виправив

2022-07-16 09:06 UTC, dmytropihur commented on ui/components/Form/Form.tsx
> +                <Link href="/login">
Виправив

2022-07-16 09:08 UTC, dmytropihur commented on ui/components/Avatar/Avatar.module.scss
> +  filter: drop-shadow(0px 0px 1px rgba(0, 0, 0, 0.5));
виправив

2022-07-16 09:08 UTC, dmytropihur commented on ui/components/Header/Header.module.scss
> +  background-color: #fff;
виправив

2022-07-16 09:11 UTC, dmytropihur commented on ui/components/Header/Header.tsx
> +        <Link href="/">
є

2022-07-16 09:38 UTC, dmytropihur commented on ui/components/Header/Header.tsx
> +              </Link>
є

2022-07-16 09:38 UTC, dmytropihur commented on ui/components/Layout/Layout.tsx
> +const Layout: NextPage<LayoutProps> = ({ children }) => {
виправив

2022-07-16 09:39 UTC, dmytropihur commented on pages/register/index.tsx
> +      router.push('/login');
є

2022-07-16 09:39 UTC, dmytropihur commented on pages/register/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
виправив

2022-07-17 09:31 UTC, dmytropihur commented on pages/register/index.tsx
> +  );
виправив

2022-07-17 09:32 UTC, dmytropihur commented on ui/styles/Login.module.scss
> +}
виправив

2022-07-17 09:32 UTC, dmytropihur commented on ui/styles/Register.module.scss
> +}
виправив

2022-07-17 09:37 UTC, dmytropihur commented on core/utils/fetchAccount.tsx
> +export default fetchAccount;
виправив

2022-07-17 09:38 UTC, dmytropihur commented on core/store/user/slice.ts
> +        // eslint-disable-next-line no-param-reassign
є

2022-07-17 10:18 UTC, dmytropihur commented on core/store/user/slice.ts
> +      const res = await axios.post(`${BASE_API_URL}/create-account`, props);
є

2022-07-17 10:18 UTC, dmytropihur commented on core/store/user/slice.ts
> +      const { headers } = await axios.post(`${BASE_API_URL}/login`, props);
є

2022-07-17 10:18 UTC, dmytropihur commented on core/config/constants.ts
> +export default BASE_API_URL;
є

2022-07-17 10:19 UTC, dmytropihur commented on ui/components/Button/Button.tsx
> +  type,
є

2022-07-17 10:20 UTC, dmytropihur commented on core/store/user/types.ts
> +  registerError: string;
виправив

2022-07-17 10:20 UTC, dmytropihur commented on core/store/user/slice.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
виправив

2022-07-17 10:20 UTC, dmytropihur commented on core/store/user/slice.ts
> +import BASE_API_URL from '../../config/constants';
виправив

2022-07-17 10:29 UTC, dmytropihur commented on ui/components/Avatar/Avatar.module.scss
> +  justify-content: center;
є

2022-07-17 14:58 UTC, dmytropihur commented on ui/components/Form/Form.tsx
> +import { AuthProps } from '../../../core/store/user/types';
є

2022-07-17 15:21 UTC, dmytropihur commented on ui/components/Avatar/Avatar.tsx
> +            />
є

2022-07-17 15:22 UTC, dmytropihur commented on ui/components/Avatar/Avatar.module.scss
> +  width: 32px;
а якщо по макету на респонсіві розмір шрифту не змінюється, як в такому випадку?

2022-07-17 15:23 UTC, dmytropihur commented on ui/components/Button/Button.tsx
> +          ? styles[`button-${variant}`]
не до кінця зрозумів, про що йдеться

2022-07-17 15:24 UTC, dmytropihur commented on ui/components/Form/Form.tsx
> +    >
якщо би так потрібно було, то зміню

2022-07-17 15:26 UTC, dmytropihur commented on pages/_app.tsx
> +        <Component {...pageProps} />
Помогло) виправив

2022-07-18 07:35 UTC, vovataras requested changes

2022-07-18 07:35 UTC, vovataras commented on core/config/constants.ts
> +};
роути варто винести в окремий файлик routes, бо їх може бути багато

2022-07-18 07:35 UTC, vovataras commented on ui/components/Avatar/Avatar.tsx
> +    <Link href="profile">
роути мають бути в константах

2022-07-18 07:35 UTC, vovataras commented on ui/components/Avatar/Avatar.tsx
> +            alt=""
не забувай про alt текст

2022-07-18 07:35 UTC, vovataras commented on ui/components/Button/Button.tsx
> +          ? styles[`button-${variant}`]
якщо параметр `variant` передається тут, як `styles['button-${variant}']`, то можна робити просто перевірку `variant ? styles[...` і `variant` затипізувати як `variant?: 'accent' | 'інші варіанти'`

2022-07-18 07:35 UTC, vovataras commented on ui/components/Form/Form.tsx
> +    >
ні, бо так також використовують

2022-07-18 07:35 UTC, vovataras commented on ui/views/Auth/index.tsx
> +  login: Yup.string().email('Invalid email').required('Required'),
правило, для login однакове, можна винести в окрему змінну

2022-07-18 07:35 UTC, vovataras commented on ui/views/Auth/index.tsx
> +      router.push('/');
роути в константи

2022-07-18 07:35 UTC, vovataras commented on ui/views/Auth/index.tsx
> +        alt=""
текст для alt

2022-07-18 07:35 UTC, vovataras commented on ui/components/Avatar/Avatar.module.scss
> +  width: 32px;
тоді ні) або зменшувати на більших пристроях (для планшетів, наприклад, або ноутбуків), а для мобільних знову повернути до звичайних розмірів

2022-07-18 07:35 UTC, vovataras commented on ui/components/Header/Header.tsx
> +        </Link>
тут можна використати, компонент LinkComponent, хіба ні?

2022-07-18 14:46 UTC, dmytropihur commented on ui/components/Button/Button.tsx
> +          ? styles[`button-${variant}`]
є

2022-07-18 14:46 UTC, dmytropihur commented on pages/_app.tsx
> +  // eslint-disable-next-line react/jsx-props-no-spreading
виправлено

2022-07-18 14:47 UTC, dmytropihur commented on ui/components/Avatar/Avatar.module.scss
> +  width: 32px;
варто це тут робити? чи просто мати наувазі?

2022-07-18 14:50 UTC, dmytropihur commented on core/config/constants.ts
> +};
є

2022-07-18 14:58 UTC, dmytropihur commented on ui/components/Avatar/Avatar.tsx
> +    <Link href="profile">
є

2022-07-18 14:58 UTC, dmytropihur commented on ui/components/Avatar/Avatar.tsx
> +            alt=""
є

2022-07-18 15:05 UTC, dmytropihur commented on ui/views/Auth/index.tsx
> +  login: Yup.string().email('Invalid email').required('Required'),
є

2022-07-18 15:05 UTC, dmytropihur commented on ui/views/Auth/index.tsx
> +      router.push('/');
є

2022-07-18 15:05 UTC, dmytropihur commented on ui/views/Auth/index.tsx
> +        alt=""
є

2022-07-18 15:21 UTC, dmytropihur commented on ui/components/Header/Header.tsx
> +        </Link>
є

2022-07-18 17:01 UTC, vovataras commented on ui/components/Avatar/Avatar.module.scss
> +  width: 32px;
просто май на увазі

2022-07-18 17:17 UTC, vovataras requested changes

2022-07-18 17:17 UTC, vovataras commented on src/core/config/constants.ts
> +  .required('Required');
це можна винести в окремий файл `validation`, чи якось так, бо це специфічна штука для валідації

2022-07-18 17:17 UTC, vovataras commented on src/ui/components/button/index.tsx
> +  variant?: string;
Протипізуй `variant` відповідно до того, які варіанти реалізовані, бо це не класнейм, де можна прийняти будь-яку стрічку. Взагалі, для базових компонент було б добре успадковувати дефолтні пропси (button має дуже багато пропсів), і щоб їх не дублювати, то можна просто об'єднати з власними пропсами.

2022-07-18 17:17 UTC, vovataras commented on src/ui/components/link/link.module.scss
> +}
ці стилі надто специфічні для такої універсальної компоненти, тому краще це розмістити в те місце, де вони використовуються

2022-07-18 17:17 UTC, vovataras commented on src/ui/components/link/index.tsx
> +  styleProp: string;
Якщо цей лінк буде мати варіанти, то варто протипізувати літералами. Стрічка - це не надійно, ти можеш помилитись в написанні, а якщо буде протипізовано, то ts підкаже, в цьому його головна фішка

2022-07-21 09:49 UTC, dmytropihur commented on src/core/config/constants.ts
> +  .required('Required');
є

2022-07-21 09:57 UTC, dmytropihur commented on src/ui/components/button/index.tsx
> +  variant?: string;
є

2022-07-21 09:59 UTC, dmytropihur commented on src/ui/components/button/index.tsx
> +  variant?: string;
є

2022-07-21 09:59 UTC, dmytropihur commented on src/ui/components/link/link.module.scss
> +}
є

2022-07-21 10:01 UTC, dmytropihur commented on src/ui/components/link/index.tsx
> +  styleProp: string;
є

2022-07-21 10:28 UTC, vovataras requested changes

2022-07-21 10:28 UTC, vovataras commented on src/ui/components/button/index.tsx
> +    >
типи для пропсів прописані, але самі пропси не прокидаються в button

2022-07-21 10:28 UTC, vovataras commented on src/ui/components/button/index.tsx
> +      } ${styles.button}`}
для зручної роботи з класнеймами є бібліотеки, які широко використовуються: `classnames` - найбільш популярна, `clsx` - менш популярна, але менше важить

2022-07-21 10:29 UTC, dmytropihur commented on src/ui/components/button/index.tsx
> +    >
є

2022-07-21 11:06 UTC, dmytropihur commented on src/ui/components/button/index.tsx
> +    >
є

2022-07-21 11:41 UTC, dmytropihur commented on src/ui/components/button/index.tsx
> +      } ${styles.button}`}
є

2022-07-21 12:29 UTC, vovataras approved these changes

2022-07-21 12:29 UTC, vovataras commented on src/ui/components/button/index.tsx
> +import cx from 'classnames';
чому `cx`?

2022-07-21 12:29 UTC, vovataras commented on src/ui/components/button/index.tsx
> +      className={cx(styles.button, styles[`button-${variant}`])}
додай ще можливість прокидати className

2022-07-21 13:24 UTC, merged