feat: create history component with redux logic
dmytropihur/linkstagram pull request #2
Opened 2022-07-21 21:00 UTC by dmytropihur

2022-07-22 08:09 UTC, vovataras requested changes

2022-07-22 08:09 UTC, vovataras commented on next.config.js
> +    },
не рекомендую поки це використовувати, чомусь воно позначено, як експериментальне

2022-07-22 08:09 UTC, vovataras commented on src/core/store/types.ts
> +};
Для загальних типів створи папку `typings` всередині `src/core/` і там вже розбивай по файлах. Файл декларацій з папки `@types` також перенеси в `typings` (назвеш якось `declaration.d.ts`) і видали папку з кореня

2022-07-22 08:09 UTC, vovataras commented on src/ui/components/avatar/index.tsx
> +import img from '@/public/images/undefined-user.svg';
що за `img`? давай розгорнутіші назви

2022-07-22 08:09 UTC, vovataras commented on src/ui/components/history-row/index.tsx
> +        profiles.map((item) => {
тут не можна використати optional operator? `profiles?.map...`

2022-07-22 08:09 UTC, vovataras commented on src/ui/components/history-row/index.tsx
> +  }, []);
це можна винести в кастомний хук (визначення розміру вікна), можеш спробувати написати його (це не вимагається, але було б добре)

2022-07-22 08:09 UTC, vovataras commented on src/ui/components/history-row/index.tsx
> +  const { profiles } = useSelector(selectProfiles);
(не обов'язково) ми часто сортуємо код в такій послідовності: селектор, стейт, хуки (якщо результатом хука є функція, або він нічого не повертає, то нижче змінних), решту змінних, useEffect, функції, рендер-методи, рендер. Порядок може змінюватись, коли useEffect, або інші хуки залежать від функцій, або інших змінних, тоді та функція чи змінна піднімається вище хука

2022-07-22 08:09 UTC, vovataras commented on src/ui/components/history-row/index.tsx
> +                size={windowSize && windowSize.innerWidth < 1024 ? 'sm' : 'md'}
також optional operator

2022-07-22 08:09 UTC, vovataras commented on src/core/store/profiles/slice.ts
> +      console.log(data);
не залишай логи в готовому коді

2022-07-22 08:09 UTC, vovataras commented on src/core/store/profiles/slice.ts
> +  profile: null,
для чого цей `profile` і де він сетається?

2022-07-22 08:09 UTC, vovataras commented on src/core/store/profiles/types.ts
> +  profile: Profile | null;
для чого цей `profile` і де він сетається?

2022-07-22 08:26 UTC, dmytropihur commented on src/core/store/profiles/slice.ts
> +  profile: null,
я думав в майбутньому це використати, для сторінки з окремим профілем, чи краще це робити через filter масиву з профілями?

2022-07-22 08:26 UTC, dmytropihur commented on src/core/store/profiles/slice.ts
> +      console.log(data);
є

2022-07-22 12:05 UTC, dmytropihur commented on next.config.js
> +    },
просто це єдиний варіант щоб в мене не додавались лині спани обгортки, в яких інлайнові стилі перебивають мої

2022-07-22 12:11 UTC, dmytropihur commented on src/core/store/types.ts
> +};
є

2022-07-22 12:12 UTC, dmytropihur commented on src/ui/components/avatar/index.tsx
> +import img from '@/public/images/undefined-user.svg';
є

2022-07-22 12:12 UTC, dmytropihur commented on src/ui/components/history-row/index.tsx
> +        profiles.map((item) => {
виправив

2022-07-22 12:27 UTC, dmytropihur commented on src/ui/components/history-row/index.tsx
> +  }, []);
є

2022-07-22 12:29 UTC, dmytropihur commented on src/ui/components/history-row/index.tsx
> +                size={windowSize && windowSize.innerWidth < 1024 ? 'sm' : 'md'}
Є

2022-07-22 12:30 UTC, dmytropihur commented on src/core/store/profiles/types.ts
> +  profile: Profile | null;
видалив

2022-07-22 12:31 UTC, dmytropihur commented on src/ui/components/history-row/index.tsx
> +  const { profiles } = useSelector(selectProfiles);
є

2022-07-25 07:33 UTC, vovataras commented on src/core/typings/status.ts
> +export type Status = 'idle' | 'pending' | 'fulfilled' | 'rejected';
цей тип стосується redux, тоді можливо є сенс назвати файл redux.ts і в майбутньому, можна буде додати ще якісь типи без перейменування файлу

2022-07-25 07:33 UTC, vovataras commented on src/ui/components/history-row/history-row.module.scss
> +  // }
якщо треба залишити, якийсь код, то залишай коментар, для чого він

2022-07-25 07:33 UTC, vovataras commented on src/ui/views/auth/index.tsx
> +import Image from 'next/future/image';
зміни на звичайний

2022-07-25 07:33 UTC, vovataras commented on next.config.js
> +    },
Image можна нормально стайлити, просто пиши більш кокретний селектор. Це правило видали

2022-07-26 14:16 UTC, dmytropihur commented on src/core/typings/status.ts
> +export type Status = 'idle' | 'pending' | 'fulfilled' | 'rejected';
є

2022-07-26 14:16 UTC, dmytropihur commented on src/ui/components/history-row/history-row.module.scss
> +  // }
видалив

2022-07-26 14:19 UTC, dmytropihur commented on src/ui/views/auth/index.tsx
> +import Image from 'next/future/image';
змінив

2022-07-26 17:17 UTC, vovataras requested changes

2022-07-26 17:17 UTC, vovataras commented on next.config.js
> +  },
чому це не видалено?

2022-08-01 17:47 UTC, vovataras requested changes

2022-08-01 17:47 UTC, vovataras commented on next.config.js
> +  reactStrictMode: false,
чому ти це відключив? воно допомагає при розробці і вказує на потенційні проблеми в додатку

2022-08-01 17:47 UTC, vovataras commented on src/core/services/api/axios.ts
> +const requestHandler = (request: any) => {
пиши краще `unknown` і уникай `any`, бо якщо писати всюди `any`, то з часом це все перетвориться на той самий `js`

2022-08-01 17:47 UTC, vovataras commented on src/core/services/api/axios.ts
> +const errorHandler = (error: any) => {
те саме і перестань відключати правила лінтера, якщо ж доводиться відключити, то питай мене, чи це якось фікситься, чи можна відключити

2022-08-01 17:47 UTC, vovataras commented on src/core/services/api/axios.ts
> +};
взагалі в чому суть цієї функції, якщо ти нічого не робиш з помилкою?

2022-08-01 17:47 UTC, vovataras commented on src/core/store/posts/types.ts
> +  posts: Post[] | null;
значення з масивами краще типізувати тільки одним типом без `null` і використовувати пустий масив `[]` як значення по замовчуванню і тоді не треба буде робити перевірку на `null`

2022-08-01 17:47 UTC, vovataras commented on src/ui/components/history-row/index.tsx
> +        // freeMode
?

2022-08-01 17:47 UTC, vovataras commented on src/ui/views/home/index.tsx
> +  }, []);
перероби на `IntersectionObserver`, він дозволяє відслідковувати зміну по конретному елементу, а лісенер на скрол відслідковує всі скроли, що негативно впливає на швидкодію сайту

2022-08-01 17:47 UTC, vovataras commented on src/ui/views/home/index.tsx
> +  );
додай якийсь лоадер в кінці списку, якщо догружаються ще пости

2022-08-02 08:12 UTC, dmytropihur commented on next.config.js
> +  reactStrictMode: false,
я це виключив на обмежений час, для перевірки правильності скролу, оскільки в стрікт моді спочатку є подвійний рендер, відповідно два рази запити робились з одної сторінки, і масив з постами невірно заповнювався

2022-08-06 16:59 UTC, dmytropihur commented on src/core/services/api/axios.ts
> +};
поправив

2022-08-06 17:16 UTC, dmytropihur commented on src/core/services/api/axios.ts
> +const errorHandler = (error: any) => {
поправив

2022-08-06 17:16 UTC, dmytropihur commented on src/core/services/api/axios.ts
> +const requestHandler = (request: any) => {
поправив

2022-08-06 17:17 UTC, dmytropihur commented on src/ui/views/home/index.tsx
> +  }, []);
використав хук для цього

2022-08-06 17:19 UTC, dmytropihur commented on src/ui/views/home/index.tsx
> +  );
є

2022-08-06 17:19 UTC, dmytropihur commented on src/ui/components/history-row/index.tsx
> +        // freeMode
видалив

2022-08-08 11:18 UTC, vovataras approved these changes

2022-08-08 11:18 UTC, vovataras commented on src/core/services/api/axios.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
видали правило

2022-08-08 11:18 UTC, vovataras commented on next.config.js
> +  reactStrictMode: false,
поверни назад до `true`, якщо вже не потрібно

2022-08-09 16:54 UTC, merged