feat: create modal component for new posts, create user profile card
dmytropihur/linkstagram pull request #4
Opened 2022-08-18 10:13 UTC by dmytropihur

2022-08-18 16:21 UTC, vovataras requested changes

2022-08-18 16:21 UTC, vovataras commented on src/ui/components/avatar/index.tsx
> +  src: string | undefined | null;
`src?: string | null;`

2022-08-18 16:21 UTC, vovataras commented on src/ui/components/modal/index.tsx
> +const Modal: React.FC<ModalProps> = ({ children, open, onClose }) => {
в 18 реакті з'явився тип `React.PropsWithChildren`, і тому в тебе вибивала помилка, коли ти звертався до children.  Якщо використовувати його так `React.PropsWithChildren<Props>` - то не треба буде додавати children явно до пропсів

2022-08-18 16:21 UTC, vovataras commented on src/ui/views/home/home.module.scss
> +  // display: flex;
?

2022-08-18 16:21 UTC, vovataras commented on src/ui/views/home/index.tsx
> +              })}
(не обов'язково в цьому випадку) таке краще виносити в змінні, тому, що в майбутньому таке легше оптимізовувати (можеш почитати собі про мемоізацію та хук useMemo) ну і іноді конструкції можуть збільшуватись до великих розмірів

2022-08-18 16:21 UTC, vovataras commented on src/ui/components/new-post/index.tsx
> +  const [imageData, setImageData] = useState({} as UppyFile);
не типізуй так, а краще як `UppyFile | null` і в такому випадку компілятор разом з IDE підкаже тобі, що воно може бути null, тому зроби перевірку. Якщо типізувати примусово, то можна провтикати перевірку і можуть бути неявні баги

2022-08-18 20:07 UTC, dmytropihur commented on src/ui/components/modal/index.tsx
> +const Modal: React.FC<ModalProps> = ({ children, open, onClose }) => {
Виправив

2022-08-18 20:08 UTC, dmytropihur commented on src/ui/components/avatar/index.tsx
> +  src: string | undefined | null;
Виправив

2022-08-18 20:08 UTC, dmytropihur commented on src/ui/views/home/home.module.scss
> +  // display: flex;
Виправив

2022-08-18 20:14 UTC, dmytropihur commented on src/ui/components/new-post/index.tsx
> +  const [imageData, setImageData] = useState({} as UppyFile);
Виправив

2022-08-19 08:28 UTC, dmytropihur commented on src/ui/views/home/index.tsx
> +              })}
Я виправив, але так як я це зрозумів)) якщо не вірно, то напиши)

2022-08-19 10:52 UTC, vovataras requested changes

2022-08-19 10:52 UTC, vovataras commented on src/ui/components/new-post/index.tsx
> +  const [imageData, setImageData] = useState({} as UppyFile | null);
знову не так, я мав на увазі такий запис:
`useState<UppyFile | null>(null)`

2022-08-19 10:52 UTC, vovataras commented on src/ui/views/home/index.tsx
> +  }, [posts]);
можна прибрати ретурни, синтаксис стрілочних функцій дозволяє

2022-08-19 10:52 UTC, vovataras commented on src/ui/views/home/index.tsx
> +  }, [posts]);
```suggestion
  const list = useMemo(
    () => posts.map((post) => <Post key={post.id} post={post} />),
    [posts],
  );
```

2022-08-19 10:55 UTC, dmytropihur commented on src/ui/components/new-post/index.tsx
> +  const [imageData, setImageData] = useState({} as UppyFile | null);
виправив

2022-08-19 10:56 UTC, dmytropihur commented on src/ui/views/home/index.tsx
> +  }, [posts]);
виправив

2022-08-19 10:56 UTC, dmytropihur commented on src/ui/views/home/index.tsx
> +  }, [posts]);
виправив

2022-08-19 10:59 UTC, vovataras approved these changes

2022-08-19 11:00 UTC, merged