Feature/delete post
dmytropihur/linkstagram pull request #5
Opened 2022-08-19 16:59 UTC by dmytropihur

2022-08-22 15:24 UTC, vovataras requested changes

2022-08-22 15:24 UTC, vovataras commented on src/ui/components/post/index.tsx
> +      </Modal>
це дуже погано, що для кожного поста створюється власна модалка, винеси її туди, де використовується список

2022-08-22 15:24 UTC, vovataras commented on src/ui/components/post/index.tsx
> +  const [isConfirmed, setIsConfirmed] = useState(false);
не розумію, для чого тут цей стан, він надлишковий, dispatch можна зробити в колбеці на конфірм

2022-08-22 15:24 UTC, vovataras commented on src/ui/components/post/index.tsx
> +    }
для чого це запихати в стейт, якщо можна просто зробити змінну?

2022-08-22 20:04 UTC, dmytropihur commented on src/ui/components/post/index.tsx
> +    }
виправив

2022-08-22 20:05 UTC, dmytropihur commented on src/ui/components/post/index.tsx
> +  const [isConfirmed, setIsConfirmed] = useState(false);
виправив

2022-08-22 20:05 UTC, dmytropihur commented on src/ui/components/post/index.tsx
> +      </Modal>
виправив

2022-08-23 10:34 UTC, vovataras requested changes

2022-08-23 10:34 UTC, vovataras commented on package.json
> +    "redux-logger": "^3.0.6",
це тільки для девелопменту потрібно, тому і розмістити пакет треба було в devDependencies

2022-08-23 10:34 UTC, vovataras commented on src/ui/views/home/index.tsx
> +    }
це хіба не хендлиться в thunk?

2022-08-23 10:34 UTC, vovataras commented on src/ui/views/home/index.tsx
> +// import selectPosts from '@/core/store/posts/selectors';
?

2022-08-23 10:40 UTC, dmytropihur commented on src/ui/views/home/index.tsx
> +// import selectPosts from '@/core/store/posts/selectors';
виправив

2022-08-23 10:40 UTC, dmytropihur commented on src/ui/views/home/index.tsx
> +    }
виправив

2022-08-23 10:40 UTC, dmytropihur commented on package.json
> +    "redux-logger": "^3.0.6",
виправив

2022-08-23 10:42 UTC, vovataras approved these changes

2022-08-23 10:42 UTC, merged