Feature/edit profile
dmytropihur/linkstagram pull request #6
Opened 2022-08-23 12:00 UTC by dmytropihur

2022-08-23 13:33 UTC, vovataras requested changes

2022-08-23 13:33 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +    },
винеси в окрему функцію і якщо ця функція не використовує дані стейтів, то можна її взагалі за межі компоненти винести

2022-08-23 13:33 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +};
винеси це в файл view.tsx, бо компонента вже дуже велика

2022-08-23 13:33 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +      console.log(values);
повидаляй логи

2022-08-23 13:33 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +  const formik = useFormik({
протипізуй явно через generic useFormik<Тип>

2022-08-23 13:33 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +              )}
серйозно? тут по суті міняється лише один проп, може варто об'єднати?

2022-08-23 13:33 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +            id="nickname"
щоб не прокидати всі пропси самому, в `formik` є функція `getFieldProps`

2022-08-23 13:33 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +        }
якщо є ерори, то виводь їх в якийсь снекбар, а не в консоль, бо користувач їх не побачить

2022-08-23 13:33 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +    },
і взагалі спрости її, код дублюється

2022-08-23 14:11 UTC, dmytropihur commented on src/ui/components/edit-profile/index.tsx
> +      console.log(values);
видалив

2022-08-23 14:14 UTC, dmytropihur commented on src/ui/components/edit-profile/index.tsx
> +  const formik = useFormik({
є

2022-08-23 14:43 UTC, dmytropihur commented on src/ui/components/edit-profile/index.tsx
> +            id="nickname"
виправив

2022-08-23 14:47 UTC, dmytropihur commented on src/ui/components/edit-profile/index.tsx
> +    },
є

2022-08-23 14:47 UTC, dmytropihur commented on src/ui/components/edit-profile/index.tsx
> +};
є

2022-08-23 15:25 UTC, dmytropihur commented on src/ui/components/edit-profile/index.tsx
> +        }
додав

2022-08-23 15:26 UTC, dmytropihur commented on src/ui/components/edit-profile/index.tsx
> +              )}
виправив

2022-08-23 16:26 UTC, vovataras requested changes

2022-08-23 16:26 UTC, vovataras commented on package.json
> +    "@mui/material": "^5.10.2",
якось закруто, лише заради одного снекбару ставити таку велику лібу, є ж окремо ліби снекбарів, наприклад, якийсь `react-toastify`

2022-08-23 16:26 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +      </Snackbar>
зроби якийсь один снекбар на весь додаток і виводи туди ерори, бо дублювати для кожного елементу, то не дуже прикольно

2022-08-23 16:26 UTC, vovataras commented on src/ui/components/edit-profile/index.tsx
> +  });
не тримай компоненти всередині інших компонент!!!

2022-08-25 17:08 UTC, vovataras approved these changes

2022-08-25 17:08 UTC, vovataras commented on package.json
> +    "redux-logger": "^3.0.6",
redux-logger - в devDependencies

2022-08-25 17:08 UTC, vovataras commented on src/ui/components/snackbar/index.tsx
> +// };
?

2022-08-25 17:08 UTC, vovataras commented on src/pages/index.tsx
> +      <Snackbar />
краще розмістити в файлі `_app` і тоді цей снекбар буде доступний для цілої апки

2022-08-25 17:36 UTC, merged